---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- name: id
  type: text
  config:
    required: false
  label: id
  hidden: true
pages:
- exampleSite/content/english/products/warm-cinema-faded-lut.md
- exampleSite/content/english/products/warm-cinema-faded-lut.md
