---
label: Product
hide_body: false
fields:
- name: id
  type: text
  config:
    required: false
  hidden: false
  label: data-item-file-guid
- type: text
  name: title
  label: title
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- name: product_url
  type: text
  config:
    required: false
  label: product_url
pages:
- exampleSite/content/english/products/warm-cinema-faded-lut.md
- exampleSite/content/english/products/warm-cinema-faded-lut.md
